project_id = "jsvduobkznoszmxedkss"

[functions.plaid-webhook]
verify_jwt = false

[functions.security-correction-task]
verify_jwt = false

[functions.team-self-register]
verify_jwt = false

[functions.create-team-invite]
verify_jwt = true

[functions.migrate-demo]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false
